#ifndef __DDNS_H__
#define __DDNS_H__
int dai_ddnsGetConfigEnable(char *value, int len);
int dai_ddnsGetOrayConfigEnable(char *value, int len);
int dai_ddnsSetConfigEnable(char *value);
int dai_ddnsSetOrayConfigEnable(char *value);
int dai_ddnsGetConfigUpdate(char *value, int len);
int dai_ddnsSetConfigUpdate(char *value);
int dai_ddnsGetConfigHostname(char *value, int len);
int dai_ddnsGetNetgearConfigHostname(char *value, int len);
int dai_ddnsGetNoipConfigHostname(char *value, int len);
int dai_ddnsGetDyndnsConfigHostname(char *value, int len);
int dai_ddnsGetPubyunConfigHostname(char *value, int len);
int dai_ddnsGetOrayConfigHostname(char *value, int len);
int dai_ddnsSetConfigHostname(char *value);
int dai_ddnsSetNetgearConfigHostname(char *value);
int dai_ddnsSetNoipConfigHostname(char *value);
int dai_ddnsSetDyndnsConfigHostname(char *value);
int dai_ddnsSetPubyunConfigHostname(char *value);
int dai_ddnsSetOrayConfigHostname(char *value);
int dai_ddnsGetConfigService(char *value, int len);
int dai_ddnsSetConfigService(char *value);
int dai_ddnsGetConfigAddress(char *value, int len);
int dai_ddnsSetConfigAddress(char *value);
int dai_ddnsGetConfigUsername(char *value, int len);
int dai_ddnsGetNetgearConfigUsername(char *value, int len);
int dai_ddnsGetNoipConfigUsername(char *value, int len);
int dai_ddnsGetNEmailConfig(char *value, int len);
int dai_ddnsGetNConfigHost(char *value, int len);
int dai_ddnsGetDyndnsConfigUsername(char *value, int len);
int dai_ddnsGetPubyunConfigUsername(char *value, int len);
int dai_ddnsGetOrayConfigUsername(char *value, int len);
int dai_ddnsGetOrayConfigDomainname(char *value, int len, int i);
int dai_ddnsSetConfigUsername(char *value);
int dai_ddnsSetNetgearConfigUsername(char *value);
int dai_ddnsSetNoipConfigUsername(char *value);
int dai_ddnsSetDyndnsConfigUsername(char *value);
int dai_ddnsSetPubyunConfigUsername(char *value);
int dai_ddnsSetOrayConfigUsername(char *value);
int dai_ddnsGetConfigPassword(char *value, int len);
int dai_ddnsGetNetgearConfigPassword(char *value, int len);
int dai_ddnsGetNoipConfigPassword(char *value, int len);
int dai_ddnsGetDyndnsConfigPassword(char *value, int len);
int dai_ddnsGetPubyunConfigPassword(char *value, int len);
int dai_ddnsGetOrayConfigPassword(char *value, int len);
int dai_ddnsSetConfigPassword(char *value);
int dai_ddnsSetNetgearConfigPassword(char *value);
int dai_ddnsSetNoipConfigPassword(char *value);
int dai_ddnsSetDyndnsConfigPassword(char *value);
int dai_ddnsSetPubyunConfigPassword(char *value);
int dai_ddnsSetOrayConfigPassword(char *value);
int dai_ddnsGetRegisteredStatus(char *value, int len);
int dai_ddnsGetUserServiceType(char *value, int len);
int dai_ddnsSetRegisteredStatus(char *value);
int dai_ddnsGetRegisteredStatuscode(char *value, int len);
int dai_ddnsSetRegisteredStatuscode(char *value);
int dai_ddnsGetRegisteredTimestamp(char *value, int len);
int dai_ddnsGetRegisteredTime(char *value, int len);
int dai_ddnsSetRegisteredTimestamp();
int dai_ddnsSetRegisteredTime();
int dai_ddnsGetRegisteredData(char *hostname, char *service, char *address);
int dai_ddnsSetRegisteredService(char *service);
int dai_ddnsSetRegisteredHostName(char *hostname);
int dai_ddnsSetConfigAddress(char *value);
int dai_ddnsGetRegisteredTimeoutTs(char *value, int len);
int dai_ddnsSetRegisteredTimeoutTs(unsigned long timeoutSec);
int dai_ddnsGetRegisteredRetryCount(char *value, int len);
int dai_ddnsSetRegisteredRetryCount(int count);
int dai_ddnsAddRegisteredRetryCount();
int dai_ddnsGetRegisteredRespInfo(char *value, int len);
int dai_ddnsSetRegisteredRespInfo(char *value);
int dai_ddnsSetRegisteredAddress(char *value);
#endif /* __DDNS_H__ */
