#!/bin/sh /etc/rc.common


setwifidebuglevel() {
	wifi2gpre=$(uci get wireless.2g.ifName 2>/dev/null)
	wifi5gpre=$(uci get wireless.5g.ifName 2>/dev/null)

	for i in $(seq 0 2); do
		iwpriv $wifi2gpre$i set Debug=$1 2>/dev/null
		iwpriv $wifi5gpre$i set Debug=$1 2>/dev/null
	done
}

start() {
	setwifidebuglevel 3
}

stop() {
	setwifidebuglevel 1
}