#!/bin/sh /etc/rc.common

#START=82
#STOP=90

USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /usr/bin/EasyMesh_openwrt.sh 0 1
	procd_close_instance
}

reload_service() {
	return 0
}

stop_service() {
	return 0
}