#!/bin/sh /etc/rc.common

START=88
STOP=01
USE_PROCD=1
PROCD_DEBUG=1

start_service() {
#    mkdir -p /fota/config
#    mkdir -p /fota/bin

    local factory_mode=$(envctl factory get factory_mode 2> /dev/null)
    if [ "$factory_mode" = "on" ]; then
        exit 0
    fi

    procd_open_instance
    procd_set_param command /usr/sbin/fota -m
    procd_set_param respawn ${respawn_threshold:-100}
    procd_close_instance

    echo "Start fota."
}

stop_service() {
    echo "Stop fota."
}
