#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

modify_kloglevel() {
    local level
    level=$(uci -q get system.@system[0].kloglevel)
    if [ "x$level" = "x" ]; then
        exit 0
    else
        echo $level 4 1 7 > /proc/sys/kernel/printk
    fi
}

start_service() {
    modify_kloglevel
}
