#!/bin/sh /etc/rc.common

START=88
STOP=01
USE_PROCD=1
PROCD_DEBUG=1

start_service() {
    procd_open_instance
    procd_set_param command /usr/sbin/powerdetection -m
    procd_set_param respawn ${respawn_threshold:-100}
    procd_close_instance

    echo "Start powerdetection."
}

stop_service() {
    echo "Stop powerdetection."
}
