#!/bin/sh /etc/rc.common

START=80
STOP=90

USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /usr/bin/wapp_openwrt.sh
	procd_close_instance
}

reload_service() {
	return 0
}

stop_service() {
	return 0
}