#ifndef __UTIL_SGW_H__
#define __UTIL_SGW_H__


#define UITL_SGW_CPK_VERSION_FAIL_ECODE -6 /* Version not right */

#define UTIL_SGW_UPGRADE_ERROR_INVALID_SOFTWARE_VERSION    1
#define UTIL_SGW_UPGRADE_ERROR_DOWNLOAD_FAIL    2
#define UTIL_SGW_UPGRADE_ERROR_NO_ENOUGH_SPACE    3
#define UTIL_SGW_UPGRADE_ERROR_OLD_SOFTWARE_VERSION    4
#define UTIL_SGW_UPGRADE_ERROR_UNKOWN    5


#endif
